# Generated by Django 5.1.5 on 2025-05-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete'), ('import', 'Import'), ('export', 'Export'), ('reset', 'Reset'), ('rfid_scan', 'RFID Scan')], max_length=10)),
                ('model', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('record_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
